version: '2'

services:
  php:
    container_name: translation_tool_php
    build: .docker/php
    volumes:
      - .:/app
    links:
      - memcached:memcached

  nginx:
    container_name: translation_tool_nginx
    build: .docker/nginx
    volumes_from:
      - php
    ports:
      - "81:80"

  memcached:
    container_name: translation_tool_memcached
    image: memcached
    ports:
      - "11211:11211"
    restart: always

  redis:
    container_name: translation_tool_redis
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always
